"""Actualizacion modulo logistica sucursales y fechas

Revision ID: 12d2d473149e
Revises: aa641e7cb8a8
Create Date: 2025-12-22 10:49:21.181014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12d2d473149e'
down_revision = 'aa641e7cb8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.String(length=255), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('folio_interno', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('numero_orden_cliente', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_documento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_recepcion', sa.Date(), nullable=True))
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('fecha_entrega_pactada',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('folio'))
        batch_op.create_unique_constraint(None, ['folio_interno'])
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])
        batch_op.drop_column('folio')
        batch_op.drop_column('fecha_solicitud')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_solicitud', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('folio', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('folio'), ['folio'], unique=True)
        batch_op.alter_column('fecha_entrega_pactada',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('fecha_recepcion')
        batch_op.drop_column('fecha_documento')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('numero_orden_cliente')
        batch_op.drop_column('folio_interno')
        batch_op.drop_column('sucursal_id')

    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.drop_column('notas')
        batch_op.drop_column('unidad_medida')

    op.drop_table('sucursales')
    # ### end Alembic commands ###
