"""Inicializando tablas de producto e inventario

Revision ID: 6ebf710ae301
Revises: 
Create Date: 2025-12-18 12:53:39.022100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebf710ae301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ancho_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('alto_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('tipos_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('tipo_material_id', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unidad_medida', sa.String(length=10), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_material_id'], ['tipos_material.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('producto_recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_consumo', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('orden_aplicacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_recetas')
    op.drop_table('materiales')
    op.drop_table('tipos_material')
    op.drop_table('productos')
    # ### end Alembic commands ###
