"""Vincular productos a clientes

Revision ID: 8130ca0830a3
Revises: d9ec779d7daf
Create Date: 2026-01-07 12:27:42.230266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8130ca0830a3'
down_revision = 'd9ec779d7daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.alter_column('codigo_interno',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('ancho_mm',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('alto_mm',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('alto_mm',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=True)
        batch_op.alter_column('ancho_mm',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=True)
        batch_op.alter_column('codigo_interno',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
