"""Agregando usuarios logistica y produccion

Revision ID: aa641e7cb8a8
Revises: 6ebf710ae301
Create Date: 2025-12-18 13:08:29.167334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa641e7cb8a8'
down_revision = '6ebf710ae301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_fiscal', sa.String(length=200), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_pactada', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cantidad_entregada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio_op', sa.String(length=20), nullable=True),
    sa.Column('pedido_detalle_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_meta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['pedido_detalle_id'], ['detalles_pedido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio_op')
    )
    op.create_table('bitacora_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_produccion_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('proceso', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('cantidad_entrada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cantidad_salida_buena', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('merma_cantidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['orden_produccion_id'], ['ordenes_produccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitacora_produccion')
    op.drop_table('ordenes_produccion')
    op.drop_table('detalles_pedido')
    op.drop_table('usuarios')
    op.drop_table('pedidos')
    op.drop_table('empleados')
    op.drop_table('clientes')
    # ### end Alembic commands ###
