"""Agregar tabla Ciudades y actualizar Clientes

Revision ID: d9ec779d7daf
Revises: 12d2d473149e
Create Date: 2026-01-07 09:33:39.776360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9ec779d7daf'
down_revision = '12d2d473149e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('colonia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('codigo_postal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ciudad_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ciudades', ['ciudad_id'], ['id'])

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colonia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('codigo_postal', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('telefono_sucursal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('transporte', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ciudad_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ciudades', ['ciudad_id'], ['id'])
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ciudad_id')
        batch_op.drop_column('transporte')
        batch_op.drop_column('telefono_sucursal')
        batch_op.drop_column('codigo_postal')
        batch_op.drop_column('colonia')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ciudad_id')
        batch_op.drop_column('codigo_postal')
        batch_op.drop_column('colonia')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')

    op.drop_table('ciudades')
    # ### end Alembic commands ###
